# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  ruby: circleci/ruby@1.4.1

jobs:
  install-ruby:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - ruby/install:
          version: '2.7.5' 
  install-deps:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - ruby/install-deps

workflows:
  example-workflow:
    jobs:
      - install-ruby
      - install-deps:
          requires:
          - install-ruby